### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by Julchen0** [rbtl-fs24/md-03-assignments-Julchen0#1]
@larnsce

**Comment by larnsce** [comment]
Thank you for completing the assignment. I have had a look at your code and it looks great. Well done. 👏🏼

You can close the issue now.

**Comment by Julchen0** [comment]
Hi @larnsce!
I just noticed that I made a mistake in the last assignment - I opened a new repository for the samples on my own GitHub Julchen0 instead of rbtl-fs24. Can you still access the data? If not, I will try my best to resolve it and will open a new repository on the rbtl-fs24 GitHub :)
But, on posit cloud, samples-Julchen0 should be at the right location. So I hope everything is fine.

**Comment by larnsce** [comment]
Hi @Julchen0, I am seeting this now. I added a description to how you can move the repo in the issue of the repository: https://github.com/Julchen0/samples-Julchen0/issues/2

You can move it. :)
